### ISSUE TITLE
Rss feed not working

### ISSUE THREAD

**Issue by umitkaraogul** [scottdorman/scottdorman.github.io#1]
Hello,
RSS feed of your blog not working (ttp://scottdorman.github.io/feed.xml)

**Comment by scottdorman** [comment]
I have updated the feed link to point to http://feeds.feedburner.com/ScottDorman and updated FeedBurner to pull from the new blog. If you were already subscribed to the feed previously (before the blog moved to GitHub) then you shouldn't need to do anything.

**Comment by umitkaraogul** [comment]
Thanks. It is working.
